import { type NextPage } from "next";
import Head from "next/head";

const Create: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Room • Group Listen</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800"></main>
      </main>
    </>
  );
};

export default Create;
