import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Spin as Hamburger } from "hamburger-react";
import {
  faGear,
  faAdd,
  faRightToBracket,
} from "@fortawesome/free-solid-svg-icons";
import { motion } from "framer-motion";
import { NavLink, NavButton } from "~/components/navButton";
import { useUser } from "@clerk/nextjs";

import { useEffect } from "react";

const Home: NextPage = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  const user = useUser();
  useEffect(() => {
    console.log(user.user);
  }, [user]);

  return (
    <>
      <Head>
        <title>Group Listen</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
        <div className=""></div>

        <div className="absolute left-8 bottom-8 flex flex-col gap-4">
          {user.isSignedIn ? (
            <>
              <NavLink
                menuOpen={menuOpen}
                closedY={150}
                icon={faGear}
                href="/setting"
              />
              <NavLink
                menuOpen={menuOpen}
                closedY={80}
                icon={faAdd}
                href="/create"
              />
            </>
          ) : (
            <NavButton
              menuOpen={menuOpen}
              closedY={80}
              icon={faRightToBracket}
            />
          )}

          <motion.button
            className="flex h-16 w-16 items-center justify-center rounded-full bg-slate-900"
            onClick={() => {
              setMenuOpen(!menuOpen);
            }}
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
          >
            <Hamburger
              toggled={menuOpen}
              toggle={setMenuOpen}
              direction="right"
              color="white"
            />
          </motion.button>
        </div>

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "></div>
      </main>
    </>
  );
};

export default Home;
