import { type NextPage } from "next";
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faRightToBracket } from "@fortawesome/free-solid-svg-icons";
import { signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

// TODO: Implement Delete Account
const deleteAccount: () => void = () => {
  toast.error("Delete Account Not Yet Implemented");
};

const Setting: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  useEffect(() => {
    if (!sessionData) void router.push("/");
  });

  return (
    <>
      <Head>
        <title>Group Listen</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center gap-2 bg-slate-800 py-8 text-white">
        <ToastContainer theme="dark" />
        {sessionData && (
          <>
            <div className="w-2/3 text-lg font-semibold">Social Setting</div>
            <div className="w-2/3 text-lg font-semibold">Account Setting</div>
            <div className="flex w-2/3 gap-2">
              <button
                className="flex w-32 flex-row items-center justify-between rounded-lg border-2 border-red-500 p-2 hover:bg-red-500"
                onClick={() => void signOut()}
              >
                Log Out
                <FontAwesomeIcon icon={faRightToBracket} className="w-4" />
              </button>
              <button
                onClick={() => void deleteAccount()}
                className="flex w-32 flex-row items-center justify-between rounded-lg bg-red-500 p-2 hover:opacity-50"
              >
                Delete Account
              </button>
            </div>
          </>
        )}
      </main>
    </>
  );
};

export default Setting;
